name: wallpaper
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod_annotation: ^1.2.1
  dio: ^4.0.6
  hooks_riverpod: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  riverpod_generator: ^1.2.0
  json_serializable: ^6.2.0
  freezed_annotation: ^2.0.3
  freezed: ^2.0.3+1

flutter:

  
  uses-material-design: true

